"""Add flexible travel fee models

Revision ID: 063f7f96be8d
Revises: s4t5u6v7w8x9
Create Date: 2026-10-03 15:34:44.009110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '063f7f96be8d'
down_revision: Union[str, Sequence[str], None] = 's4t5u6v7w8x9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('travel_fee_mode', sa.String(), nullable=False, server_default="per_km"))
    op.add_column('providers', sa.Column('fixed_travel_fee', sa.Numeric(precision=10, scale=2), nullable=False, server_default="0.00"))
    op.add_column('providers', sa.Column('travel_distance_tiers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'travel_distance_tiers')
    op.drop_column('providers', 'fixed_travel_fee')
    op.drop_column('providers', 'travel_fee_mode')
    # ### end Alembic commands ###
