"""extend_outbox_and_device_token

Revision ID: 082c179fc570
Revises: 872af49ef6c4
Create Date: 2026-07-08 14:03:44.021986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '082c179fc570'
down_revision: Union[str, Sequence[str], None] = '872af49ef6c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_tokens', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_device_tokens_tenant_id'), 'device_tokens', ['tenant_id'], unique=False)
    op.add_column('outbox_events', sa.Column('tenant_id', sa.String(), nullable=True))
    op.add_column('outbox_events', sa.Column('status', sa.String(), nullable=False))
    op.add_column('outbox_events', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('outbox_events', sa.Column('error_log', sa.Text(), nullable=True))
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_index(op.f('ix_outbox_events_tenant_id'), 'outbox_events', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_events_tenant_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_column('outbox_events', 'error_log')
    op.drop_column('outbox_events', 'retry_count')
    op.drop_column('outbox_events', 'status')
    op.drop_column('outbox_events', 'tenant_id')
    op.drop_index(op.f('ix_device_tokens_tenant_id'), table_name='device_tokens')
    op.drop_column('device_tokens', 'tenant_id')
    # ### end Alembic commands ###
