"""add_tenant_id_to_packages_and_plugins

Revision ID: 0ad8693fe61e
Revises: ab69f4da7ff6
Create Date: 2026-07-22 03:05:13.962179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ad8693fe61e'
down_revision: Union[str, Sequence[str], None] = 'ab69f4da7ff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugin_states', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_plugin_states_name'), table_name='plugin_states')
    op.create_index(op.f('ix_plugin_states_name'), 'plugin_states', ['name'], unique=False)
    op.create_index(op.f('ix_plugin_states_tenant_id'), 'plugin_states', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_plugin_state_tenant_name', 'plugin_states', ['tenant_id', 'name'])
    op.create_foreign_key(None, 'plugin_states', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('service_packages', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_service_packages_tenant_id'), 'service_packages', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'service_packages', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_packages', type_='foreignkey')
    op.drop_index(op.f('ix_service_packages_tenant_id'), table_name='service_packages')
    op.drop_column('service_packages', 'tenant_id')
    op.drop_constraint(None, 'plugin_states', type_='foreignkey')
    op.drop_constraint('uq_plugin_state_tenant_name', 'plugin_states', type_='unique')
    op.drop_index(op.f('ix_plugin_states_tenant_id'), table_name='plugin_states')
    op.drop_index(op.f('ix_plugin_states_name'), table_name='plugin_states')
    op.create_index(op.f('ix_plugin_states_name'), 'plugin_states', ['name'], unique=True)
    op.drop_column('plugin_states', 'tenant_id')
    # ### end Alembic commands ###
