"""add_image_to_service

Revision ID: 2f379fcbe18c
Revises: 0ad8693fe61e
Create Date: 2026-07-26 07:04:48.537237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f379fcbe18c'
down_revision: Union[str, Sequence[str], None] = '0ad8693fe61e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'image')
    # ### end Alembic commands ###
