"""add_image_to_location

Revision ID: 5eb4cf78175f
Revises: 2f379fcbe18c
Create Date: 2026-07-28 08:07:27.595308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eb4cf78175f'
down_revision: Union[str, Sequence[str], None] = '2f379fcbe18c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'image')
    # ### end Alembic commands ###
