"""add_sms_module

Revision ID: 62202d3e7aa6
Revises: ef32705b90fe
Create Date: 2026-08-25 20:02:32.930736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62202d3e7aa6'
down_revision: Union[str, Sequence[str], None] = 'ef32705b90fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('transport_type', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('sender_address', sa.String(), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('autoresponder_enabled', sa.Boolean(), nullable=False),
    sa.Column('autoresponder_text', sa.Text(), nullable=True),
    sa.Column('ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('ai_mode', sa.String(), nullable=False),
    sa.Column('line_prompt', sa.Text(), nullable=True),
    sa.Column('catchup_cutoff_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_accounts_id'), 'sms_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_sms_accounts_provider_id'), 'sms_accounts', ['provider_id'], unique=False)
    op.create_index(op.f('ix_sms_accounts_public_id'), 'sms_accounts', ['public_id'], unique=True)
    op.create_index(op.f('ix_sms_accounts_tenant_id'), 'sms_accounts', ['tenant_id'], unique=False)
    op.create_table('sms_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('sms_account_id', sa.Integer(), nullable=False),
    sa.Column('customer_address', sa.String(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sms_account_id'], ['sms_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sms_account_id', 'customer_address', name='uq_sms_account_customer')
    )
    op.create_index(op.f('ix_sms_conversations_customer_address'), 'sms_conversations', ['customer_address'], unique=False)
    op.create_index(op.f('ix_sms_conversations_id'), 'sms_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_sms_conversations_provider_id'), 'sms_conversations', ['provider_id'], unique=False)
    op.create_index(op.f('ix_sms_conversations_sms_account_id'), 'sms_conversations', ['sms_account_id'], unique=False)
    op.create_index(op.f('ix_sms_conversations_tenant_id'), 'sms_conversations', ['tenant_id'], unique=False)
    op.create_table('sms_inbound_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sms_account_id', sa.Integer(), nullable=False),
    sa.Column('event_key', sa.String(), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sms_account_id'], ['sms_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_inbound_receipts_event_key'), 'sms_inbound_receipts', ['event_key'], unique=True)
    op.create_index(op.f('ix_sms_inbound_receipts_id'), 'sms_inbound_receipts', ['id'], unique=False)
    op.create_index(op.f('ix_sms_inbound_receipts_sms_account_id'), 'sms_inbound_receipts', ['sms_account_id'], unique=False)
    op.create_table('sms_knowledge_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('sms_account_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('provenance', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sms_account_id'], ['sms_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_knowledge_entries_id'), 'sms_knowledge_entries', ['id'], unique=False)
    op.create_index(op.f('ix_sms_knowledge_entries_provider_id'), 'sms_knowledge_entries', ['provider_id'], unique=False)
    op.create_index(op.f('ix_sms_knowledge_entries_sms_account_id'), 'sms_knowledge_entries', ['sms_account_id'], unique=False)
    op.create_index(op.f('ix_sms_knowledge_entries_tenant_id'), 'sms_knowledge_entries', ['tenant_id'], unique=False)
    op.create_table('sms_prompt_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('sms_account_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sms_account_id'], ['sms_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_prompt_profiles_id'), 'sms_prompt_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_sms_prompt_profiles_provider_id'), 'sms_prompt_profiles', ['provider_id'], unique=False)
    op.create_index(op.f('ix_sms_prompt_profiles_sms_account_id'), 'sms_prompt_profiles', ['sms_account_id'], unique=False)
    op.create_index(op.f('ix_sms_prompt_profiles_tenant_id'), 'sms_prompt_profiles', ['tenant_id'], unique=False)
    op.create_table('sms_ai_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('customer_turn_ref', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['sms_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_ai_jobs_conversation_id'), 'sms_ai_jobs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_sms_ai_jobs_customer_turn_ref'), 'sms_ai_jobs', ['customer_turn_ref'], unique=False)
    op.create_index(op.f('ix_sms_ai_jobs_id'), 'sms_ai_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_sms_ai_jobs_status'), 'sms_ai_jobs', ['status'], unique=False)
    op.create_table('sms_conversation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['sms_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_conversation_events_conversation_id'), 'sms_conversation_events', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_sms_conversation_events_id'), 'sms_conversation_events', ['id'], unique=False)
    op.create_index(op.f('ix_sms_conversation_events_type'), 'sms_conversation_events', ['type'], unique=False)
    op.create_table('sms_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('sms_account_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('normalized_body', sa.Text(), nullable=True),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('author_type', sa.String(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('provider_message_id', sa.String(), nullable=True),
    sa.Column('parent_message_id', sa.Integer(), nullable=True),
    sa.Column('client_request_id', sa.String(), nullable=True),
    sa.Column('customer_turn_ref', sa.String(), nullable=True),
    sa.Column('ai_metadata', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['sms_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_message_id'], ['sms_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sms_account_id'], ['sms_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_messages_client_request_id'), 'sms_messages', ['client_request_id'], unique=False)
    op.create_index(op.f('ix_sms_messages_conversation_id'), 'sms_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_sms_messages_customer_turn_ref'), 'sms_messages', ['customer_turn_ref'], unique=False)
    op.create_index(op.f('ix_sms_messages_id'), 'sms_messages', ['id'], unique=False)
    op.create_index(op.f('ix_sms_messages_provider_id'), 'sms_messages', ['provider_id'], unique=False)
    op.create_index(op.f('ix_sms_messages_provider_message_id'), 'sms_messages', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_sms_messages_sms_account_id'), 'sms_messages', ['sms_account_id'], unique=False)
    op.create_index(op.f('ix_sms_messages_tenant_id'), 'sms_messages', ['tenant_id'], unique=False)
    op.create_table('sms_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['sms_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_notes_conversation_id'), 'sms_notes', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_sms_notes_id'), 'sms_notes', ['id'], unique=False)
    op.create_table('sms_arrival_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['sms_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_arrival_sessions_booking_id'), 'sms_arrival_sessions', ['booking_id'], unique=True)
    op.create_index(op.f('ix_sms_arrival_sessions_conversation_id'), 'sms_arrival_sessions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_sms_arrival_sessions_id'), 'sms_arrival_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sms_arrival_sessions_token'), 'sms_arrival_sessions', ['token'], unique=True)
    op.create_table('sms_delivery_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['sms_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_delivery_receipts_id'), 'sms_delivery_receipts', ['id'], unique=False)
    op.create_index(op.f('ix_sms_delivery_receipts_message_id'), 'sms_delivery_receipts', ['message_id'], unique=False)
    op.create_table('sms_outbound_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('sms_account_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['sms_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sms_account_id'], ['sms_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_outbound_jobs_id'), 'sms_outbound_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_sms_outbound_jobs_message_id'), 'sms_outbound_jobs', ['message_id'], unique=False)
    op.create_index(op.f('ix_sms_outbound_jobs_sms_account_id'), 'sms_outbound_jobs', ['sms_account_id'], unique=False)
    op.create_index(op.f('ix_sms_outbound_jobs_status'), 'sms_outbound_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sms_outbound_jobs_status'), table_name='sms_outbound_jobs')
    op.drop_index(op.f('ix_sms_outbound_jobs_sms_account_id'), table_name='sms_outbound_jobs')
    op.drop_index(op.f('ix_sms_outbound_jobs_message_id'), table_name='sms_outbound_jobs')
    op.drop_index(op.f('ix_sms_outbound_jobs_id'), table_name='sms_outbound_jobs')
    op.drop_table('sms_outbound_jobs')
    op.drop_index(op.f('ix_sms_delivery_receipts_message_id'), table_name='sms_delivery_receipts')
    op.drop_index(op.f('ix_sms_delivery_receipts_id'), table_name='sms_delivery_receipts')
    op.drop_table('sms_delivery_receipts')
    op.drop_index(op.f('ix_sms_arrival_sessions_token'), table_name='sms_arrival_sessions')
    op.drop_index(op.f('ix_sms_arrival_sessions_id'), table_name='sms_arrival_sessions')
    op.drop_index(op.f('ix_sms_arrival_sessions_conversation_id'), table_name='sms_arrival_sessions')
    op.drop_index(op.f('ix_sms_arrival_sessions_booking_id'), table_name='sms_arrival_sessions')
    op.drop_table('sms_arrival_sessions')
    op.drop_index(op.f('ix_sms_notes_id'), table_name='sms_notes')
    op.drop_index(op.f('ix_sms_notes_conversation_id'), table_name='sms_notes')
    op.drop_table('sms_notes')
    op.drop_index(op.f('ix_sms_messages_tenant_id'), table_name='sms_messages')
    op.drop_index(op.f('ix_sms_messages_sms_account_id'), table_name='sms_messages')
    op.drop_index(op.f('ix_sms_messages_provider_message_id'), table_name='sms_messages')
    op.drop_index(op.f('ix_sms_messages_provider_id'), table_name='sms_messages')
    op.drop_index(op.f('ix_sms_messages_id'), table_name='sms_messages')
    op.drop_index(op.f('ix_sms_messages_customer_turn_ref'), table_name='sms_messages')
    op.drop_index(op.f('ix_sms_messages_conversation_id'), table_name='sms_messages')
    op.drop_index(op.f('ix_sms_messages_client_request_id'), table_name='sms_messages')
    op.drop_table('sms_messages')
    op.drop_index(op.f('ix_sms_conversation_events_type'), table_name='sms_conversation_events')
    op.drop_index(op.f('ix_sms_conversation_events_id'), table_name='sms_conversation_events')
    op.drop_index(op.f('ix_sms_conversation_events_conversation_id'), table_name='sms_conversation_events')
    op.drop_table('sms_conversation_events')
    op.drop_index(op.f('ix_sms_ai_jobs_status'), table_name='sms_ai_jobs')
    op.drop_index(op.f('ix_sms_ai_jobs_id'), table_name='sms_ai_jobs')
    op.drop_index(op.f('ix_sms_ai_jobs_customer_turn_ref'), table_name='sms_ai_jobs')
    op.drop_index(op.f('ix_sms_ai_jobs_conversation_id'), table_name='sms_ai_jobs')
    op.drop_table('sms_ai_jobs')
    op.drop_index(op.f('ix_sms_prompt_profiles_tenant_id'), table_name='sms_prompt_profiles')
    op.drop_index(op.f('ix_sms_prompt_profiles_sms_account_id'), table_name='sms_prompt_profiles')
    op.drop_index(op.f('ix_sms_prompt_profiles_provider_id'), table_name='sms_prompt_profiles')
    op.drop_index(op.f('ix_sms_prompt_profiles_id'), table_name='sms_prompt_profiles')
    op.drop_table('sms_prompt_profiles')
    op.drop_index(op.f('ix_sms_knowledge_entries_tenant_id'), table_name='sms_knowledge_entries')
    op.drop_index(op.f('ix_sms_knowledge_entries_sms_account_id'), table_name='sms_knowledge_entries')
    op.drop_index(op.f('ix_sms_knowledge_entries_provider_id'), table_name='sms_knowledge_entries')
    op.drop_index(op.f('ix_sms_knowledge_entries_id'), table_name='sms_knowledge_entries')
    op.drop_table('sms_knowledge_entries')
    op.drop_index(op.f('ix_sms_inbound_receipts_sms_account_id'), table_name='sms_inbound_receipts')
    op.drop_index(op.f('ix_sms_inbound_receipts_id'), table_name='sms_inbound_receipts')
    op.drop_index(op.f('ix_sms_inbound_receipts_event_key'), table_name='sms_inbound_receipts')
    op.drop_table('sms_inbound_receipts')
    op.drop_index(op.f('ix_sms_conversations_tenant_id'), table_name='sms_conversations')
    op.drop_index(op.f('ix_sms_conversations_sms_account_id'), table_name='sms_conversations')
    op.drop_index(op.f('ix_sms_conversations_provider_id'), table_name='sms_conversations')
    op.drop_index(op.f('ix_sms_conversations_id'), table_name='sms_conversations')
    op.drop_index(op.f('ix_sms_conversations_customer_address'), table_name='sms_conversations')
    op.drop_table('sms_conversations')
    op.drop_index(op.f('ix_sms_accounts_tenant_id'), table_name='sms_accounts')
    op.drop_index(op.f('ix_sms_accounts_public_id'), table_name='sms_accounts')
    op.drop_index(op.f('ix_sms_accounts_provider_id'), table_name='sms_accounts')
    op.drop_index(op.f('ix_sms_accounts_id'), table_name='sms_accounts')
    op.drop_table('sms_accounts')
    # ### end Alembic commands ###
