"""add_record_keeping_fields

Revision ID: 989cd554d405
Revises: 480974c4f0a5
Create Date: 2026-07-09 00:22:43.276722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '989cd554d405'
down_revision: Union[str, Sequence[str], None] = '480974c4f0a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_time_blocked', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_visible', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('capacity', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('color', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_visible', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('deposit_amount', sa.Float(), server_default='0.0', nullable=False))
        batch_op.add_column(sa.Column('tax_rate_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('min_group_size', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('max_group_size', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_services_tax_rates', 'tax_rates', ['tax_rate_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint('fk_services_tax_rates', type_='foreignkey')
        batch_op.drop_column('max_group_size')
        batch_op.drop_column('min_group_size')
        batch_op.drop_column('tax_rate_id')
        batch_op.drop_column('deposit_amount')
        batch_op.drop_column('is_visible')

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('color')
        batch_op.drop_column('capacity')
        batch_op.drop_column('is_visible')

    with op.batch_alter_table('calendar_notes', schema=None) as batch_op:
        batch_op.drop_column('is_time_blocked')
        batch_op.drop_column('note_type')
    # ### end Alembic commands ###
