"""add_active_and_visibility_fields

Revision ID: c37a157ed3b1
Revises: 5eb4cf78175f
Create Date: 2026-07-28 18:44:35.964091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c37a157ed3b1'
down_revision: Union[str, Sequence[str], None] = '5eb4cf78175f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default='1' is required for SQLite - cannot add NOT NULL columns without a default
    op.add_column('add_ons', sa.Column('is_visible', sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('categories', sa.Column('is_visible', sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('locations', sa.Column('active', sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('locations', sa.Column('is_visible', sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('products', sa.Column('is_visible', sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('service_packages', sa.Column('is_visible', sa.Boolean(), nullable=False, server_default='1'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_packages', 'is_visible')
    op.drop_column('products', 'is_visible')
    op.drop_column('locations', 'is_visible')
    op.drop_column('locations', 'active')
    op.drop_column('categories', 'is_visible')
    op.drop_column('add_ons', 'is_visible')
    # ### end Alembic commands ###
