"""add_remediation_fields

Revision ID: c4d31b16692d
Revises: 3ffd6b0bbcaf
Create Date: 2026-07-12 11:03:33.286075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4d31b16692d'
down_revision: Union[str, Sequence[str], None] = '3ffd6b0bbcaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_categories_category_id'), 'location_categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_location_categories_id'), 'location_categories', ['id'], unique=False)
    op.create_index(op.f('ix_location_categories_location_id'), 'location_categories', ['location_id'], unique=False)
    op.create_index(op.f('ix_location_categories_tenant_id'), 'location_categories', ['tenant_id'], unique=False)
    op.create_table('location_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_providers_id'), 'location_providers', ['id'], unique=False)
    op.create_index(op.f('ix_location_providers_location_id'), 'location_providers', ['location_id'], unique=False)
    op.create_index(op.f('ix_location_providers_provider_id'), 'location_providers', ['provider_id'], unique=False)
    op.create_index(op.f('ix_location_providers_tenant_id'), 'location_providers', ['tenant_id'], unique=False)
    op.create_table('location_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_services_id'), 'location_services', ['id'], unique=False)
    op.create_index(op.f('ix_location_services_location_id'), 'location_services', ['location_id'], unique=False)
    op.create_index(op.f('ix_location_services_service_id'), 'location_services', ['service_id'], unique=False)
    op.create_index(op.f('ix_location_services_tenant_id'), 'location_services', ['tenant_id'], unique=False)
    op.create_table('management_review_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('preferred_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('slot_reserved', sa.Boolean(), nullable=False),
    sa.Column('payment_taken', sa.Boolean(), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_management_review_requests_client_id'), 'management_review_requests', ['client_id'], unique=False)
    op.create_index(op.f('ix_management_review_requests_id'), 'management_review_requests', ['id'], unique=False)
    op.create_index(op.f('ix_management_review_requests_tenant_id'), 'management_review_requests', ['tenant_id'], unique=False)
    op.add_column('audit_logs', sa.Column('tenant_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.add_column('bookings', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_bookings_idempotency_key'), 'bookings', ['idempotency_key'], unique=True)
    op.add_column('clients', sa.Column('management_approval_required', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('clients', sa.Column('restriction_reason', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('restricted_by_id', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('restricted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('clients', sa.Column('restriction_cleared_by_id', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('restriction_cleared_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invoices', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_invoices_idempotency_key'), 'invoices', ['idempotency_key'], unique=True)
    op.add_column('notification_templates', sa.Column('tenant_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_index(op.f('ix_notification_templates_tenant_id'), 'notification_templates', ['tenant_id'], unique=False)
    op.add_column('notifications', sa.Column('tenant_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.add_column('providers', sa.Column('ignore_company_hours', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('reminder_rules', sa.Column('tenant_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_index(op.f('ix_reminder_rules_tenant_id'), 'reminder_rules', ['tenant_id'], unique=False)
    op.add_column('services', sa.Column('max_advance_days', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('timezone', sa.String(), nullable=False, server_default='UTC'))
    op.add_column('tenants', sa.Column('country', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('email', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('website', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('public_address_visibility', sa.String(), nullable=False, server_default='visible'))
    op.add_column('tenants', sa.Column('max_advance_days', sa.Integer(), nullable=False, server_default='60'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'max_advance_days')
    op.drop_column('tenants', 'public_address_visibility')
    op.drop_column('tenants', 'website')
    op.drop_column('tenants', 'phone')
    op.drop_column('tenants', 'email')
    op.drop_column('tenants', 'country')
    op.drop_column('tenants', 'timezone')
    op.drop_column('services', 'max_advance_days')
    op.drop_index(op.f('ix_reminder_rules_tenant_id'), table_name='reminder_rules')
    op.drop_column('reminder_rules', 'tenant_id')
    op.drop_column('providers', 'ignore_company_hours')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_column('notifications', 'tenant_id')
    op.drop_index(op.f('ix_notification_templates_tenant_id'), table_name='notification_templates')
    op.drop_column('notification_templates', 'tenant_id')
    op.drop_index(op.f('ix_invoices_idempotency_key'), table_name='invoices')
    op.drop_column('invoices', 'idempotency_key')
    op.drop_column('clients', 'restriction_cleared_at')
    op.drop_column('clients', 'restriction_cleared_by_id')
    op.drop_column('clients', 'restricted_at')
    op.drop_column('clients', 'restricted_by_id')
    op.drop_column('clients', 'restriction_reason')
    op.drop_column('clients', 'management_approval_required')
    op.drop_index(op.f('ix_bookings_idempotency_key'), table_name='bookings')
    op.drop_column('bookings', 'idempotency_key')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'tenant_id')
    op.drop_index(op.f('ix_management_review_requests_tenant_id'), table_name='management_review_requests')
    op.drop_index(op.f('ix_management_review_requests_id'), table_name='management_review_requests')
    op.drop_index(op.f('ix_management_review_requests_client_id'), table_name='management_review_requests')
    op.drop_table('management_review_requests')
    op.drop_index(op.f('ix_location_services_tenant_id'), table_name='location_services')
    op.drop_index(op.f('ix_location_services_service_id'), table_name='location_services')
    op.drop_index(op.f('ix_location_services_location_id'), table_name='location_services')
    op.drop_index(op.f('ix_location_services_id'), table_name='location_services')
    op.drop_table('location_services')
    op.drop_index(op.f('ix_location_providers_tenant_id'), table_name='location_providers')
    op.drop_index(op.f('ix_location_providers_provider_id'), table_name='location_providers')
    op.drop_index(op.f('ix_location_providers_location_id'), table_name='location_providers')
    op.drop_index(op.f('ix_location_providers_id'), table_name='location_providers')
    op.drop_table('location_providers')
    op.drop_index(op.f('ix_location_categories_tenant_id'), table_name='location_categories')
    op.drop_index(op.f('ix_location_categories_location_id'), table_name='location_categories')
    op.drop_index(op.f('ix_location_categories_id'), table_name='location_categories')
    op.drop_index(op.f('ix_location_categories_category_id'), table_name='location_categories')
    op.drop_table('location_categories')
    # ### end Alembic commands ###
