"""add_image_to_provider_category_addon_product_package

Revision ID: ef32705b90fe
Revises: c37a157ed3b1
Create Date: 2026-07-28 20:52:15.675135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef32705b90fe'
down_revision: Union[str, Sequence[str], None] = 'c37a157ed3b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('add_ons', sa.Column('image', sa.String(), nullable=True))
    op.add_column('categories', sa.Column('image', sa.String(), nullable=True))
    op.add_column('products', sa.Column('image', sa.String(), nullable=True))
    op.add_column('providers', sa.Column('image', sa.Text(), nullable=True))
    op.add_column('service_packages', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_packages', 'image')
    op.drop_column('providers', 'image')
    op.drop_column('products', 'image')
    op.drop_column('categories', 'image')
    op.drop_column('add_ons', 'image')
    # ### end Alembic commands ###
